package isi.dds.tp.enums;

public enum EnumCondicionIVA {
	RESPONSABLE_INSCRIPTO, 
	RESPONSABLE_NO_INSCRIPTO, 
	NO_RESPONSABLE, 
	SUJETO_EXENTO, 
	CONSUMIDOR_FINAL, 
	RESPONSABLE_MONOTRIBUTO,
	SUJETO_NO_CATEGORIZADO, 
	IVA_LIBERADO, 
	MONOTRIBUTISTA_SOCIAL
}
