INSERT INTO marca (id_marca, nombre) VALUES
(NEXTVAL('id_marca_seq'), 'Volkswagen'),
(NEXTVAL('id_marca_seq'), 'Fiat'),
(NEXTVAL('id_marca_seq'), 'Ford'),
(NEXTVAL('id_marca_seq'), 'Alfa Romeo'),
(NEXTVAL('id_marca_seq'), 'Audi'),
(NEXTVAL('id_marca_seq'), 'MBW'),
(NEXTVAL('id_marca_seq'), 'Chery'),
(NEXTVAL('id_marca_seq'), 'Chevrolet'),
(NEXTVAL('id_marca_seq'), 'Chrysler'),
(NEXTVAL('id_marca_seq'), 'Citroën'),
(NEXTVAL('id_marca_seq'), 'Dodge'),
(NEXTVAL('id_marca_seq'), 'Ferrari'),
(NEXTVAL('id_marca_seq'), 'Honda'),
(NEXTVAL('id_marca_seq'), 'Hyundai'),
(NEXTVAL('id_marca_seq'), 'Jaguar'),
(NEXTVAL('id_marca_seq'), 'Jeep'),
(NEXTVAL('id_marca_seq'), 'Kia'),
(NEXTVAL('id_marca_seq'), 'Land Rover'),
(NEXTVAL('id_marca_seq'), 'Mercedes Benz'),
(NEXTVAL('id_marca_seq'), 'Mitsubishi'),
(NEXTVAL('id_marca_seq'), 'Nissan'),
(NEXTVAL('id_marca_seq'), 'Peugeot'),
(NEXTVAL('id_marca_seq'), 'Porsche'),
(NEXTVAL('id_marca_seq'), 'Seat'),
(NEXTVAL('id_marca_seq'), 'Susuki'),
(NEXTVAL('id_marca_seq'), 'Toyota'),
(NEXTVAL('id_marca_seq'), 'Volvo');

INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Amarok', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Bora', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Caddy', marquita1, indice) INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Fox', marquita, indice) INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Gol', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Golf', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Multivan', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'New Beetle', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Passat', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Polo', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Santana', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Saveiro', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Voyage', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Vento', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Up', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Transporter', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'The Beetle', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'T-Cross', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Suran', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Sharan', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Scirocco', marquita1, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);

INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), '500', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), '500X', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Argo', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Bravo', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Cronos', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Dobló', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Ducato', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Fiorino', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Fiorino QUBO', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Grand Siena', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Idea', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Linea', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Marea', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Mobi', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Palio', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);

INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Palio Adventure', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Punto', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Qubo', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Siena', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Stilo', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Strada', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Tipo', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Toro', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Uno', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Uno EVO', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Weekend', marquita2, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);

INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Courier', marquita3, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'EcoSport', marquita3, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'EcoSport KD', marquita3, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'F-100', marquita3, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Fiesta', marquita3, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Fiesta KD', marquita3, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Focus', marquita3, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Focus III', marquita3, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'KA', marquita3, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Kuga', marquita3, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Mondeo', marquita3, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Mustang', marquita3, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Ranger', marquita3, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'S-Max', marquita3, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Transit', marquita3, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);

INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), '147', marquita4, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), '159', marquita4, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Brera', marquita4, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Giulia', marquita4, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Giulietta', marquita4, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'GT', marquita4, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Mito', marquita4, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Spider', marquita4, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Stelvio', marquita4, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);

INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'A1', marquita5, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'A3', marquita5, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'A4', marquita5, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'A5', marquita5, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'A6', marquita5, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'A7', marquita5, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'A8', marquita5, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Allroad', marquita5, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Q2', marquita5, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Q3', marquita5, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Q5', marquita5, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Q7', marquita5, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'R8', marquita5, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'TT', marquita5, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);

INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Serie 1', marquita6, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Serie 2', marquita6, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Serie 3', marquita6, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Serie 4', marquita6, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Serie 5', marquita6, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Serie 6', marquita6, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Serie 7', marquita6, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Serie 8', marquita6, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'X1', marquita6, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'X2', marquita6, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'X3', marquita6, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'X4', marquita6, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Z4', marquita6, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);

INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Arrizo 5', marquita7, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Face', marquita7, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Fulwin', marquita7, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Fulwin 2', marquita7, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'QQ', marquita7, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Skin', marquita7, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Tiggo', marquita7, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Tiggo 2', marquita7, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Tiggo 3', marquita7, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);
INSERT INTO modelos VALUES (NEXTVAL('id_modelo_seq'), 'Tiggo 5', marquita7, indice); INSERT INTO anio_modelo VALUES (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice), (NEXTVAL('id_anio_modelo_seq'), ANIIOS, SUMITA, CURRVAL('id_modelo_seq'), indice); INSERT INTO riesgo_modelo (id, inicio_vigencia, ultimo, valor_porcentual, id_modelo, idx) VALUES (NEXTVAL('id_riesgo_modelo_seq'), '2019-10-23', true, riesguito, CURRVAL('id_modelo_seq'), indice);